-- Schema for User entity (matches com.telconovaP7F22025.demo.model.User)
-- Table: usuarios
CREATE TABLE IF NOT EXISTS usuarios (
	id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email_usuario VARCHAR(255) NOT NULL,
	password_usuario VARCHAR(255) NOT NULL,
	name_usuario VARCHAR(255) NOT NULL,
	role_usuario VARCHAR(255) NOT NULL
);

-- Unique constraint on email
ALTER TABLE usuarios ADD CONSTRAINT IF NOT EXISTS uk_usuarios_email UNIQUE (email_usuario);

-- Schema for Technician entity (matches com.telconovaP7F22025.demo.model.Technician)
-- Table: tecnicos
CREATE TABLE IF NOT EXISTS tecnicos (
	id_tecnico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name_tecnico VARCHAR(255) NOT NULL,
	zone_tecnico VARCHAR(255) NOT NULL,
	workload_tecnico VARCHAR(255) NOT NULL,
	speciality_tecnico VARCHAR(255) NOT NULL
);

-- Unique constraint on name_tecnico
ALTER TABLE tecnicos ADD CONSTRAINT IF NOT EXISTS uk_tecnicos_name UNIQUE (name_tecnico);

-- Schema for Orders entity (used by frontend dashboard)
-- Table: ordenes
CREATE TABLE IF NOT EXISTS ordenes (
  id VARCHAR(32) PRIMARY KEY,
  zona VARCHAR(255) NOT NULL,
  creado_en TIMESTAMP NOT NULL,
  servicio VARCHAR(255) NOT NULL,
  descripcion VARCHAR(2000) NOT NULL,
  assigned_to VARCHAR(64),
  status VARCHAR(32) NOT NULL
);
